site:
  title: Trobador Transformation Engine
  url: https://jam01.github.io/trobador
  start_page: datasonnet::index.adoc
content:
  sources:
  - url: .
    branches: HEAD
    start_path: docs
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true

  # see: https://docs.antora.org/antora/2.3/publish-to-github-pages/#use-the-supplemental-ui
  supplemental_files:
      - path: ui.yml
        contents: |
          static_files: [ .nojekyll ]
      - path: .nojekyll
