name: ci

on: [push]

jobs:
  build:
    # skip releases
    if: startsWith(github.ref, '[maven-release-plugin] prepare release') != true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # needed for license-plugin to check last modified date of each file
          fetch-depth: 0
      - name: Set up JDK
        uses: oracle-actions/setup-java@v1
        with:
          website: jdk.java.net
          release: 19
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: mvn clean verify
        run: mvn -V --no-transfer-progress --batch-mode clean verify
