name: ci

on: [push]

jobs:
  build:
    # skip releases
    if: startsWith(github.ref, '[maven-release-plugin] prepare release') != true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # needed for license-plugin to check last modified date of each file
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'
      - name: mvn clean verify
        run: mvn -V --no-transfer-progress --batch-mode clean verify
