name: docs
on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/docs.yaml'
jobs:
  build_site:
    name: "Build mkdocs site"
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - shell: bash
        run: |
          pip install mkdocs-material mkdocs-minify-plugin
      - run: mkdocs gh-deploy --force
