name: docs
on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/docs.yaml'
jobs:
  build_site:
    name: "Build mkdocs site"
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - shell: bash
        run: pip install mkdocs-material mkdocs-minify-plugin
      - uses: actions/setup-node@v3
        with:
          node-version: latest
      - shell: bash
        run: |
          npm --prefix playground/ install
          npm --prefix playground/ start
      - run: mkdocs gh-deploy --force
